### PR TITLE
fix: preserve multiline formatting in flag descriptions

### LINKED ISSUE #70: Flatterned rendering for multiline flag description
### Description

Trying to add a multi-line description to a flag, but ends up as a single line.

### Setup

OS: Ubuntu 25.04 x86_64
Shell: bash
Terminal: ghostty
Terminal Multiplexer: N/A

### To Reproduce

Without loss of generality, adding the flag from the Docker CLI,

```
	cmd.Flags().String("format", "f", `Pretty-print the output using a Go template or one of the following special values
'table':            Print output in table format with column headers (default)
'table TEMPLATE':   Print output in table format using the given Go template
'json':             Print in JSON format
'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates`)
```
### Current behavior

Image

### Expected behavior

Using cobra directly:

Image

### PR DESCRIPTION
**Pull request by caarlos0**
## Summary
- Fixes issue where multiline flag descriptions were being flattened into a single line
- Preserves line breaks and proper indentation for continuation lines
- Maintains backward compatibility with single-line descriptions

## Test plan
- [x] Added comprehensive test case with golden files
- [x] All existing tests pass
- [x] Manual testing with example program shows correct multiline formatting
- [x] Verified default values are properly appended to the last line

💖 Generated with Crush

closes #70

### CODE REVIEW

File: example/main.go [hunk 1]
```diff
@@ -85,6 +85,12 @@ echo 'foo' |
 	cmd.Flags().Float64Var(&baz, "idk", 0.0, "I don't know")
 	cmd.Flags().BoolP("async", "a", false, "Run async")
 	cmd.Flags().BoolVarP(&eerr, "error", "e", false, "Makes the program exit with error")
+	cmd.Flags().String("format", "table", `Pretty-print the output using a Go template or one of the following special values
+'table':            Print output in table format with column headers (default)
+'table TEMPLATE':   Print output in table format using the given Go template
+'json':             Print in JSON format
+'TEMPLATE':         Print output using the given Go template.
```
Comment (ccoVeille) [inline example/main.go:92]: The difference between table template and template is not clear

Even by reading the documentation link ypu provided

Comment (caarlos0) [reply example/main.go:92]: this is just an example to test fang, its not real :)
